export const GET_ACCOUNTS_START = 'GET_ACCOUNTS_START';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL';

export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const SELECT_FRIEND = 'SELECT_FRIEND';

export const GET_CONVO_START = 'GET_CONVO_START';
export const GET_CONVO_SUCCESS = 'GET_CONVO_SUCCESS';
export const GET_CONVO_FAIL = 'GET_CONVO_FAIL';

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';